"""empty message

Revision ID: 5eea0a14b72d
Revises: e65043684c27
Create Date: 2021-11-18 00:27:45.651621

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5eea0a14b72d'
down_revision = 'e65043684c27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('full_name', sa.String(length=100), nullable=False))
    op.drop_column('contact', 'fullname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('fullname', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('contact', 'full_name')
    # ### end Alembic commands ###
